ARG BASE_IMAGE="ubuntu"
ARG TAG="22.04"
FROM ${BASE_IMAGE}:${TAG} as build


ARG DEBIAN_FRONTEND=noninteractive
ARG USER_NAME=ardupilot
ARG USER_UID=1000
ARG USER_GID=1000
ARG SKIP_AP_EXT_ENV=1
ARG SKIP_AP_GRAPHIC_ENV=1
ARG SKIP_AP_COV_ENV=1
ARG SKIP_AP_GIT_CHECK=1
WORKDIR /${USER_NAME}

RUN groupadd ${USER_NAME} --gid ${USER_GID}\
    && useradd -l -m ${USER_NAME} -u ${USER_UID} -g ${USER_GID} -s /bin/bash

RUN apt-get update && apt-get install --no-install-recommends -y \
    lsb-release \
    ca-certificates \
    sudo \
    tzdata \
    bash-completion \
    git
# Create non root user for pip
ENV USER=${USER_NAME}

RUN echo "ardupilot ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME}
RUN chmod 0440 /etc/sudoers.d/${USER_NAME}

RUN chown -R ${USER_NAME}:${USER_NAME} /${USER_NAME}

USER ${USER_NAME}

# Clone the Ardupilot files
ARG COPTER_TAG=HF_Copter-4.5

# install git 
# RUN git config --global url."https://github.com/".insteadOf git://github.com/

# Now grab ArduPilot from GitHub
RUN git clone -b ${COPTER_TAG} --single-branch https://github.com/HoverflyHampton/ardupilot.git
WORKDIR /${USER_NAME}/ardupilot

# Now start build instructions from http://ardupilot.org/dev/docs/setting-up-sitl-on-linux.html
RUN git submodule update --init --recursive


# setup for SITL
ENV SKIP_AP_EXT_ENV=$SKIP_AP_EXT_ENV SKIP_AP_GRAPHIC_ENV=$SKIP_AP_GRAPHIC_ENV SKIP_AP_COV_ENV=$SKIP_AP_COV_ENV SKIP_AP_GIT_CHECK=$SKIP_AP_GIT_CHECK
RUN Tools/environment_install/install-prereqs-ubuntu.sh -y
RUN ./waf distclean
RUN ./waf configure --board sitl
RUN ./waf copter

# Expose the SIM mavlink port
EXPOSE 5760/tcp

# Variables for simulator
ENV INSTANCE 0
ENV SYSID 1
ENV LAT 28.80498009382373
ENV LON -81.31741091852288
ENV ALT 14
ENV DIR 270
ENV MODEL +
ENV SPEEDUP 1
ENV VEHICLE ArduCopter

ENTRYPOINT ["/bin/bash", "-c", "/ardupilot/ardupilot/Tools/autotest/sim_vehicle.py --vehicle ${VEHICLE} -I${INSTANCE} --sysid ${SYSID} --custom-location=${LAT},${LON},${ALT},${DIR} -w --frame ${MODEL} --no-mavproxy --no-rebuild --out --speedup ${SPEEDUP}"]